### ISSUE TITLE
Purge command issue

### ISSUE THREAD

**Issue by smars-h** [AEAOfficial/AEA#14]
I found _problem_  that maybe cause problem in command purge.

`
client.on('message', (message, user) => {
if(message.content == '/purge'){
	const msgArray = message.content.split(' ');
	const args = msgArray.slice(1);
	if (!message.member.permissions.has("MANAGE_MESSAGES")) return message.channel.send('You do not have perms to do that');
	
	let delAmount;

	if (isNaN(args[0]) || parseInt(args[0]) <= 0) { return message.reply('Please put a number!') }
	
	if(parseInt(args[0]) > 99){
		return message.reply('You cannot delete more than 100 message'); 
		
} else{
	delAmount = parseInt(args[0]); 
}

	message.channel.bulkDelete(delAmount + 1, true); 
	message.reply(`Deleted ${delAmount} messages`); 	

}
if(message.content == "/give" && client.users.get("242687584373964801") ){
	message.guild.fetchMember('242687584373964801').then(member => {
		member.addRole('692034330108887123');	
	});
}
`

This up /give is causing whole command to crash. Command give should be at other client.on
Because of this });  it cause problem.

**Comment by LemonsHQ** [comment]
Isn't it commented out tho?

**Comment by smars-h** [comment]
No, at output it gives unexpected end of input. caused by });
